version: '3.3'
services:
  seanime:
    image: 5rahim/seanime:latest
    container_name: seanime
    volumes:
      - 1000:/collection
      - 1000:/config
    ports:
      - 43211:43211
    environment:
      - SEANIME_DATA_DIR=/config
      - SEANIME_SERVER_HOST=0.0.0.0
      - SEANIME_SERVER_PORT=43211
      - PUID=<puid>
      - PGID=<pgid>
    restart: unless-stopped
    network_mode: "host"
